### ISSUE TITLE
Dúvida?

### ISSUE THREAD

**Issue by Marcos-Development-web** [mariasmoUN/portafolio#1]
Hola, tu portafolio es increíble, una duda donde puedo conseguir svg como los que usaste

**Comment by mariasmoUN** [comment]
Hola! Muchas gracias por tu comentario
Las imagenes las configuré yo en Canva, ahí hay muchas plantillas y formas que puedes hacer para crear los tuyos 😄

**Comment by Marcos-Development-web** [comment]
> 

Ok, muchas gracias
