### ISSUE TITLE
sobre el readme

### ISSUE THREAD

**Issue by Marcos-Development-web** [mariasmoUN/portafolio#2]
si no es mucha molestia, tienes la plantilla en el canva de tu archivo readme donde pones la imagen de tu sitio dentro del escritorio, laptop, tablet.....

**Comment by mariasmoUN** [comment]
Hola! 
no tengo la plantilla como tal, todo lo hago en un solo proyecto, pero he creado una que si te puedo compartir, puedes editarla, solo tienes que subir las imagenes de las pantallas de tus proyectos y las acomodas a los tamaños de los dispositivos, hay escritorio, laptop, tablet y móvil 

[Link Plantilla de Canva](https://www.canva.com/design/DAFYHwPyDls/dd9vNzOB3QZSq17amzTGBw/edit?utm_content=DAFYHwPyDls&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Espero sea de tu ayuda y si necesitas ayuda con algo no dudes en decirme.

**Comment by Marcos-Development-web** [comment]
ahhh muchas gracias, esto ayuda mucho, les deseo mucha prosperidad gracias
