### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Do-not-existing** [mariasmoUN/portafolio#3]
Woww que portfólio maravilhoso, você é muito habilidosa em front-end, a propósito qual a largura e altura da imagem no readme?? Eu coloco imagem recortada do site mais fica gigante ocupa muito espaço

**Comment by mariasmoUN** [comment]
Hola! Muchas gracias por tus palabras. La imagen del Readme tiene una dimensión de 1093 x 615, espero esas medida te sirvan, saludos!

**Comment by Do-not-existing** [comment]
Ok, muito obrigada 😊😊
